### ISSUE TITLE
TypeError when editing width

### ISSUE THREAD

**Issue by kanitw** [uwdata/lyra#119]
**Steps**
1) Choose Barley dataset, add rect marks.
2) Drag `year` to *width* and `site` to *height*.
3) Change End to width.  Somehow width’s default is 0.   
   Note that width’s default is not bonded to a scale (unlike height #117). 
4) change width’s value to any number then the width section is broken

![lyra-40](https://f.cloud.github.com/assets/111269/2224852/d8d4809c-9a83-11e3-99fd-af8dff8d2157.png)

with the following errors:
```
TypeError: Cannot set property 'value' of undefined
    at kb (http://localhost/lyra/js/lib/angular-1.2.10.min.js:86:43)
    at t.assign (http://localhost/lyra/js/lib/angular-1.2.10.min.js:161:248)
    at $setViewValue (http://localhost/lyra/js/lib/angular-1.2.10.min.js:174:225)
    at http://localhost/lyra/js/lib/angular-1.2.10.min.js:125:486
    at h.$eval (http://localhost/lyra/js/lib/angular-1.2.10.min.js:102:308)
    at h.$apply (http://localhost/lyra/js/lib/angular-1.2.10.min.js:103:48)
    at HTMLInputElement.h (http://localhost/lyra/js/lib/angular-1.2.10.min.js:125:466)
    at HTMLInputElement.st.event.dispatch (http://localhost/lyra/js/lib/jquery.min-1.9.0.js:2:5418)
    at HTMLInputElement.$event.dispatch (http://localhost/lyra/js/lib/jquery.event.drag-2.2.js:374:20)
    at HTMLInputElement.y.handle (http://localhost/lyra/js/lib/jquery.min-1.9.0.js:2:2126) angular-1.2.10.min.js:84
```

Use case: suppose I want to draw rect with fixed width and use position as encoding.  
(I try to draw examples with text here…)
```
A     [——]

B            [——]

C       [——]

D                 [——]
```

**Comment by arvind** [comment]
Dropzone decisions are deferred to Vega-Lite now!
