### ISSUE TITLE
Cannot load vega spec into editor mode

### ISSUE THREAD

**Issue by domoritz** [uwdata/lyra#214]
```
TypeError: Cannot read property 'transforms' of undefined
    at Object.vde.Vis.parse.parse.mark (http://idl.cs.washington.edu/projects/lyra/app/js/vis.js:4289:19)
    at Array.forEach (native)
    at Function.vde.Vis.parse.parse.container (http://idl.cs.washington.edu/projects/lyra/app/js/vis.js:4243:24)
    at http://idl.cs.washington.edu/projects/lyra/app/js/vis.js:4232:13
    at Array.forEach (native)
    at Function.vde.Vis.parse.parse.layers (http://idl.cs.washington.edu/projects/lyra/app/js/vis.js:4219:16)
    at Object.parse (http://idl.cs.washington.edu/projects/lyra/app/js/vis.js:3958:11)
    at http://idl.cs.washington.edu/projects/lyra/app/js/app.js:667:13
    at h.$get.h.$eval (http://idl.cs.washington.edu/projects/lyra/app/js/lib/angular-1.2.10.min.js:102:308)
    at h.$get.h.$apply (http://idl.cs.washington.edu/projects/lyra/app/js/lib/angular-1.2.10.min.js:103:48)
```

At the last point `pipeline` is undefined because `mark.from.data` is undefined. 

I'm not exactly sure what the problem is but it could be that the vega spec is too new. See discussion in https://github.com/uwdata/vegalite-ui/issues/7

JsFiddle: http://jsfiddle.net/h64Lonf6/3/

**Comment by arvind** [comment]
@RussellSprouts could you take a look at this? From what I can tell, the parser is creating a default layer and then trying to put the marks into it. However, this spec already has a group mark at the top-level and then normal marks underneath it. So that group mark should be promoted to a layer in Lyra.

**Comment by RussellSprouts** [comment]
Currently, Lyra uses the special property "lyra.groupType" to distinguish between layers and groups. If we add "lyra.groupType": "layer" to the group mark, it loads successfully. See http://jsfiddle.net/h64Lonf6/4/

I debated both ways of detecting groups. On one hand, it is nice when it is automatic, but Lyra layers are much more restricted than groups -- they can only have constant sizes, no data bindings.

**Comment by domoritz** [comment]
Thanks! The `lyra.groupType` flag works for now. Btw, is there a way to detect onload across domains to avoid the timeout hack?

**Comment by arvind** [comment]
I'd like to keep this open until we improve importing Vega specifications as discussed above.

**Comment by arvind** [comment]
Lyra 2's model corresponds much more closely to an actual Vega spec. So, hopefully such hacks will no longer be necessary.
